### ISSUE TITLE
Users should be anonymous, yet still uniquely identifiable

### ISSUE THREAD

**Issue by stovsky** [ldalton02/cs130-project2#24]
## User Story
As a **User**, I would like **to chat anonymously but identifiably** so that **other people know I am the same person chatting, but without revealing my true identity**.

## Detailed Description
Users should be associated with an anonymous username, this way people know they are conversing with the same person. For example we could do something like Verb + Noun, like Dancing Kangaroo.  This could be the same for a user across all places, or each place can be a new identifier for a user.

## Acceptance Criteria
- [ ] Given **a user**, then **an anonymous identifier is associated with that user**

**Comment by ldalton02** [comment]
@stovsky What are your thoughts on simply assigning a user a random animal name when they sign up? Could get a large amount of animal names (>100?) to make enough for many identifiable users, and permanently assign someone this when signing  up

**Comment by stovsky** [comment]
@ldalton02 I think this would work, but obviously will encounter issues when we reach a lot of users.  Also it may be important for a user to have unique anonymity across places, so they can have a different persona at different locations. However, I think it ultimately depends on the experience we want, since it also could be equally as valid for users to want to build their reputation in the area with the same anonymous name.

**Comment by ldalton02** [comment]
@stovsky Discussed offline, users will be able to change their "avatar" once per 24 hours
