### ISSUE TITLE
Each post must be able to be voted on and stay visible for a short period of time (24 hours)

### ISSUE THREAD

**Issue by mwehrenberg** [ldalton02/cs130-project2#26]

**Comment by mwehrenberg** [comment]
<img width="495" alt="Screenshot 2024-02-22 at 4 40 38 PM" src="https://github.com/ldalton02/cs130-project2/assets/16083978/90ce06d5-186e-4b74-b365-93fd4696e570">
Enabled up and down voting

**Comment by ldalton02** [comment]
@mwehrenberg Merged pull request
