### ISSUE TITLE
Create development environment

### ISSUE THREAD

**Issue by stovsky** [ldalton02/cs130-project2#5]
## User Story
As a **Developer**, I would like **to setup the Next.js environment** so that **I can start building the app and creating more complex components**.

## Detailed Description
To begin building the app, we first need to setup the base Next.js environment so we can start developing our functionalities.

## Acceptance Criteria
- [x] Given **a developer wishes to work on a new feature**, then **they can clone the respository and build the project without any issues**

**Comment by Bivtor** [comment]
# Working in the Dev Environment
* Navigate to the bruin-banter/ directory and run 'npm run dev' for a live view of your work
## Creating Pages
* To create a new web page, create a .tsx file under the src/app
* Use the previous homepage as a template if you don't have experience with the TSX functional components syntax
* Write your HTML code in the 'return ()' section
## Styling Pages
* To write front end code, create NAME.module.scss files in the styles/scss/ directory.
* Open another terminal, navigate to bruin-banter/styles/ and run the command `sass -w --no-source-map scss/:css/`
* You can follow my more in-depth tutorial on writing front end code [here](https://docs.google.com/document/d/1p7qv8TZX7zhecYrCeHj_Z5Dl-pVZxCJDQr9KGesI1BM/edit)
## Writing Back End Code
* Next.js extends the native fetch Web API
* You can write code to fetch data above the 'return()' portion of a .tsx page
* Example from Next.JS: 
```
async function getData() {
  const res = await fetch('https://api.example.com/...')
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.
 
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }
 
  return res.json()
}
 
export default async function Page() {
  const data = await getData()
 
  return <main></main>
}
```
* I am less familiar with the layout of this newer version of Next.JS, so following [this section](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-client-with-route-handlers) of Next.JS's tutorial may be helpful
